### ISSUE TITLE
how to debug app?

### ISSUE THREAD

**Issue by mjsf12** [sds100/KeyMapper#179]

**Comment by sds100** [comment]
Are you trying to run the debug build from Android Studio?

**Comment by mjsf12** [comment]
I'm trying to get a log to understand a bug from my gamepad. maybe debug is not the right word.
sorry my English.

**Comment by sds100** [comment]
What is the bug? Maybe I can help resolve it. You should be able to install Android Studio, download the project as a zip from GitHub, extract the zip and open it the folder in Android Studio, then run the app.

**Comment by mjsf12** [comment]
@sds100 
![WhatsApp Image 2019-05-06 at 20 21 11](https://user-images.githubusercontent.com/1287082/57531767-97811180-7310-11e9-9de2-5e90aa898aa8.jpeg)
in this activity when I click on record and I click in the button (dpad gamepad), it changes the selected button and it does not record.
sorry my English.
gamepad : ipega 9099

**Comment by sds100** [comment]
Oh, okay. The problem is either: the accessibility is somehow not able to listen to keyevents and needs restarting or its the design flaw with how buttons are recorded. It could be a similar problem to why Android TV's can't record triggers since they can't click to stop recording since all keyevents are being consumed.

**Comment by sds100** [comment]
I am adding a system which logs main events (e.g when a key is consumed) within the app to a text file and an activity to see it since there are a lot of issues between devices.
