### ISSUE TITLE
Allow modifers to be held

### ISSUE THREAD

**Issue by germ** [sds100/KeyMapper#304]
Love this little bit of software and am looking forward to using it on my Unihertz Titan :) 

Just one feature request, when matching a send for a modifier (Alt, Meta, Shift, Etc) keep it active until that key is released. 

An example is using Shift on Z, if you map it using keyremapper it will correctly send Shift but when the next keypress comes in the shift is released! Keeping the mod down until Z comes up would be awesome and go a long way towards bringing QMK style actions to KeyMapper :)

Also a compact view for all the shortcuts would be nice, once you have 10+ it can get very cluttered!

**Comment by sds100** [comment]
Hi! :)

Sorry but I don't quite understand the issue. Is it a bug or a feataure request for something new? Does it have anything to do with issue #238?
And what do you mean by "shortcuts"? The list items for each keymap, which are displayed on the homescreen of the app?

**Comment by germ** [comment]
Oh jeez, I missed that other request. The modifier stuff is covered by #238 

What I meant with the other part was a kind of 'only if pressed with another' action. So the mapping is something like
Z (held) -> Shift
Z (pressed) -> Z

For devices with smaller keyboards that's very useful :)

>The list items for each keymap, which are displayed on the homescreen of the app?
Yup those! Once you have bunch of the the UI becomes very hard to navigate

Thanks again for the solid program!

**Comment by sds100** [comment]
Oh, okay. So if you remap a long press of Z to shift, it should type Z on a short press?

**Comment by sds100** [comment]
And about the simpler layout, could you help me with #299? I'd like some feedback on potential designs.

**Comment by germ** [comment]
Exactly. For small keyboards such as the BlackBerry Key2, Passport or Unihertz Titan it's a great way of extending the keyboard with very few keys available.

**Comment by sds100** [comment]
there is a problem with detecting long presses in an accessibility service. The accessibility service receives a KeyEvent when a key is pressed down and another when it is released but it doesn't tell me whether it is long pressed. Therefore, I have to do that long-press detection logic myself. The problem arises because Android does what a key is supposed to do only when it receives the _down_ event. For me to detect a long press, I have to "consume" the down event (i.e don't let Android see that it happened, which stops the key doing its normal short-press action) and then wait for the _up_ event so I can calculate how long the key was pressed down. If it is pressed down long enough, I perform the action you told the key to do on a long-press. If the key was _not_ long pressed, I have to perform the action it is supposed to do on a short press but there is no reliable way to determine what a key is supposed to do by its keycode.

**Comment by sds100** [comment]
The feature request is already implemented but has a limitation which isn't always clear.
