### ISSUE TITLE
Suggestion to add an option for Auto-Press, Unlock Long Press Delay, and floating overlay to instantly disable key-maps.

### ISSUE THREAD

**Issue by TheTerrarian101** [sds100/KeyMapper#318]
**Auto-Press** - An option to have the key (Ex: volume up or Q) auto pressed so we don't have to hold down the button ourselves, it can help automate tasks and can be a helpful assist in some cases. An overlay to disable and enable the key-map(s) would also be useful for this.

**Unlock Long Press Delay** - Currently the lowest we can go is 100ms, an option to unlock this and make the lowest 0 would be handy to make key-maps operate instantly making some tasks easier and more efficient.

**Floating Overlay** - A floating overlay option would be much more preferred in my opinion as it is faster than opening the notification bar to pause mappings.  Options to change Opacity, Color, Background, and Size could make the overlay experience better.

**Folders?** - Folders to hold separate key-maps could be useful as users can have separate key-maps for different topics and uses like spamming, auto-typing, auto-clicking, etc. It'd also be easier to enable multiple key-maps at once.

Thank you for reading through this
- Founder

**Comment by sds100** [comment]
Hello,

Thank you for the suggestions. I have already unlocked the long press delay and it will come in the next update. The minimum will be 1 because if it is 0, then it isn't a long press and the keymap should just be a short press.

Folders sounds like a good idea and will add that. I'll add the backend for it in the next update and then the front end in an update afterwards so I don't have to deal with database migration. Should folders have any other attributes besides the keymaps stored within them? I guess being able to enable/disable a folder is useful.

Would you want an action to auto-press? E.g have an action to repeatedly press a customisable keyevent?

The overlay is the biggest task so I'd like to get all the other smaller features in first.

**Comment by TheTerrarian101** [comment]
You're welcome for the suggestions and if i have more I'll gladly send (if they're any good).

The Auto-Press is something my friend and I would use and would love to see in the app. There could be different settings like Press delay or Hold Down. In some apps the key-mapper could be used as an auto-clicker that doesn't mess with your touch (as regular auto-clickers can sometimes prevent certain actions like movement or freeze the device) or as an easy text repeater if you and your friend are having some kind of weird contest (my friend and i do not do that but i have seen others do it).

I understand the overlay difficulty and/or tedious coding process, smaller features would probably be best for now until everything is set.

**Comment by sds100** [comment]
Keep adding the suggestions! there are so many I need to work on... i really need someone to help.

By press delay do you mean the delay between each repeat?
By "hold down" do you mean if the trigger has to be held down for the action to work instead of just pressing the trigger and letting the action repeat?

**Comment by TheTerrarian101** [comment]
Yes
It Auto holds down the button for us so we wouldn't have to
Like if we set Volume up to "Q" it will just hold down volume up so we wouldn't have to, then it'll be spamming Q as if we're holding down on it, so it goes along with the Long Press Delay.

**Comment by sds100** [comment]
If you don't have to hold down the keys, when should the repeating stop?

**Comment by TheTerrarian101** [comment]
> If you don't have to hold down the keys, when should the repeating stop?

It can be a switch, press to activate/deactivate
And/or have a persistent notification

**Comment by sds100** [comment]
ohh, yeah. good idea. I'll do the switch at first and I'll integrate it into the overlay once I've added the overlay.

**Comment by TheTerrarian101** [comment]
> ohh, yeah. good idea. I'll do the switch at first and I'll integrate it into the overlay once I've added the overlay.

Awesome

**Comment by sds100** [comment]
moved to individual issues. see #319 #320 #321 #237
