### ISSUE TITLE
3 Questions and Theme Suggestions

### ISSUE THREAD

**Issue by TheTerrarian101** [sds100/KeyMapper#323]
**Question(s):**
1. Is it possible to add support where you don't need to use the keyboard as long as you have something else connected that is being used, like a controller or keyboard?
2. Will you ever create a discord server for the app(s)? _Can be used for Beta Releases, Announcements, and easier chatting._
3. When can we expect a possible release date for the next update?

**Suggestion(s):**
- Amoled/Black Theme
- Dark Theme
- RGB Theme (For Background and/or Borders)

-- Founder

**Comment by sds100** [comment]
1. The Key Mapper keyboard only has to be chosen if you are remapping a long press of "keyboard" keys or want to use certain actions. It is the only way to make these things work on Android (without root). I will add support to make these features work with root.
2. Yeah, I'll create a discord server and have a link for it in the app.
3. hopefully ill have a suitable beta in the next few weeks. you can already try out the alpha builds in the Github Actions page. They are built everytime I commit. I think I'm half way there with doing the keymap detection algorithm and once that it is done, all the core functionality of the app is done.

I have added a dark theme in the next update. You can try it out! I don't plan on adding any custom theming options since it is too much work considering the user won't spend much time in the app.

**Comment by TheTerrarian101** [comment]
1. Alright
2. Nice
3. Looking forward for the next update and beta
Yesss lol
