### ISSUE TITLE
remap fingerprint gestures

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#378]
This can't be combined with other keys.
add the option to remap fingerprint gestures to the same section in the app for the bixby button. #118 

- [x] Disable the button to remap fingerprint gestures if fingerprintgestures aren't supported or it hasn't been checked whether they are supported.
- [x] Limit to Android O API 26 and devices that can detect gestures. 
- [x] FingerprintKeymap class. properties: action, extras, flags.
- [x] store in shared prefs with custom serializer and deserializer.
- [x] Have a checkbox to "repeat until swiped again". allow repeat rate option when this is checked. _Not_ repeat delay because the fingerprint gesture can't be held down.
- [x] Vibrate and vibrate duration options.
- [x] constraints. add a "Add Constraint" button 
- [x] accessibility service flags: `flagDefault|flagRequestFingerprintGestures android:canRequestFingerprintGestures="true"`
- [x] use `fingerprintGestureController.isGestureDetectionAvailable` to determine whether fingerprint gesture is supported.
- [x] ~~everytime the accessibility service starts, save whether gesture detection is available to sharedprefs. When the screen for special buttons is opened and the accessibility service hasn't been turned on to determine whether gestures are supported and `FingerprintManagerCompat.isHardwareDetected`returns true, show a dialog prompting the user to turn on the accessibility service to see if gestures are supported. Title = "Fingerprint hardware detected"~~
- [x] option to enable/disable.
- [x] make disable all and enable all button change these keymaps as well
- [x] react to pausing/resuming keymaps
- [x] backup and restore. Add a button to backup everything next to "restore" button. Move the pause/resume button to the bottom of the menu.
- [x] hide tabs and disable swiping when multi selecting
- [x] add slide in AppIntro letting the user know that they have to enable the accessibility service for Key Mapper to check if fingerprint is supported. 
Show a "Check" button, which will turn on the accessibility service. Show a toast message when they come back to the app saying whether fingerprint is supported.
Only show this on Android Oreo+
- [x] fix jank when swiping to the fingerprint gesture fragment for the first time
- [x] allow an action list
- [ x] ~~add constraint list and action list header~~
- [x] put at the top of the app description.
- [x] add all old configkeymapfragments. e.g constraintsandmore, triggerandactions etc 
- [x] create custom action options for action shortcuts
- [x] remove usage of singleliveevent
- [x] test on pre Oreo
- [x] hold down until swiped again

**Comment by sds100** [comment]
implemented

**Comment by TechMan205** [comment]
Your app is very very very good which is a big under statment cuz knowing just great and powerful it really is its of Elite status a very world class high extreme in quality kind of app it is beyond powerful its dev is what his app is world it fully even trancends how far any remapper in Existence can possibly ever go which is pretty far no doubt and well by now we all know it can make a top 10 - 5or 20 in powerful of all time for android or which ever os in general by far its amongst The Most powerful apps in google play such as tasker which probably is the most powerful and macrodroid a powerful and very popular app in its own right my issue with it is it advertise having a touch id actions feature but is appearantly removed what fan asked for its removal if a fan did obviously their not much or at all in their right mind cuz adding a feature and removing it for any reason at all is Like filling a bucket with a hole in it just very very very dumb and pointless cuz if a hacker took away it will be understanble or acceptable in a way but not a dev of his app so i doubt such a smart dev will do such a nonsensical thing to his very own app/creation especially without a Need to cuz imagine combining it with a button just imagine how very cool it is or if it can do multi actions by merging actions to happen 1 by 1 after a next  known as a macro or sequqnce of commands i also prefer actions and add key in 1 place in its main page

**Comment by TechMan205** [comment]
my advice bro as i truly do wanna see your app/this app Level all of the way up so it can get so so much better and go further i know It has got very very far now but in Life all knows there is just always further to go & enough is just never Enough untill every spot is clean now with all being said your app is not flawless by no means which its very understandable cuz its just Life And nothing in it really is or can be it how ever is not ever a good excuse at all ever to not give a try with all your best all out style if you ask me which so ever That your creation is you always need to simply believe in it cuz if it wasnt for you it will not exist wether its a child product /item / object of any matter or king cuz if you believe in it which ever thing it is can be as great as you desire 1 day eventually this app is already a big success reaching thousands then as much as 1m plus users many ppl uses it for gaming minecraft or which ever android game it is in elite./Level/league class im sure of that well it dont need much all it need is #1 updating skiping 1 or 2 months than updating by the next approaching month number 2 which is of a Great & high Level of imporance will be touch id gestures its a must Have top Main Feature its possibly best of all which is due to how important such feature is third must do is a macro sequence of actions aka sequence of commands it is my favorite cuz it combines multiple actions and stuff in to doing something of a much higher value than normal id rank it undesputedly number 3 must do and feature fingerprint is nearly as good but nothing beats macros its why tasker is androids most powerful app duh obviously right i know and even voice assistants which are all macro based apps since they can do multi actions by using just voice as a trigger  just imagine macros and combining a button with fingerprint id Long press and double press or normal tap gestures or finger id swiping gestures too

**Comment by TechMan205** [comment]
im sure or i believe you may just know tv quick actions which is a full tv remapper first & only tv based remapper fully 100% made for tvs id much prefer him aquiring key mapper if you handed this app over i am sure it will do much better in thriving and keeping up with time & android which gets an update as quick as every 2 year or so which means this app may not work in a couple years an app needs updates in order to replenish  and Live on in which it will be stabilized enough to run flawlessly as it could on older and new devices cuz android inc has announced they will be cutting support in all older devices tv quick action dev is a very very very hard working app dev that i just cant imagine or see in  my head will just randomly give up on such a top tier world class elite powerful app just as if its a dumb joke or a dumb toy it will be in a thriving direction with nothing holding it back or down with Lazy behavior he will understand its an app millions uses by daily basis and respect us all who uses it as fans of his hard work cuz the work a guy or girl did while Living is what youll remmember him or her by for ever & always

**Comment by TechMan205** [comment]
anyways there is a very slight or fair possibility in which you can still merge touch id gestures as hard or impossible it will semm with a button which is by adding a plus to an added button with action which is gonna take you to a built in readily added type of fp gesture or in reverse with an already recordded button since you cant record it Like you can with few buttons did yk fingerprint gestures do exist in button styles for an example Long hold tap a double tap and single tap on touch id will do stuff with it normally works regardless of which device and how it is wired but is swipes that usually dont we need it cuz many of us just dont wanna mess with our vol buttons we usually need it always why use vol buttons when ppl can use a different kind of trigger which is only useful or works at all by default on Lockscreen or in stand by i mean you can unlock what is already opened/unlocked so it will not do shit in Launcher or any app but a finger print remapping app will make it do something on Launcher or in any app
