### ISSUE TITLE
Does this support NFC buttons?

### ISSUE THREAD

**Issue by fuckkgithub** [sds100/KeyMapper#436]
I'm looking to buy NFC buttons to control media on my phone, but ones like DIMPLE.IO and Air Button seem to require proprietary apps. Can they be mapped with Key Mapper instead?

**Comment by sds100** [comment]
Hi,

if it is something that can plug into the headphone jack and just acts like the headset button on a pair of wired earphones then it might be remappable. I'm not 100% sure though. I think you will have to bite the bullet and hope for the best. I'm going to close this issue since there isn't anything I can do if they use a proprietary interface.
