### ISSUE TITLE
make consuming keyevents optional per trigger key

### ISSUE THREAD

**Issue by cauerego** [sds100/KeyMapper#474]
when setting a trigger with pressing shift first, in any key combination, that will make holding shift to select text to completely stop working.

**Comment by sds100** [comment]
Would the option to not override the default behaviour of the trigger buttons fix the problem for you? It is in the 2.1 Beta 1 release as an option in the last tab when configuring a keymap. The reason why I consume the down keyevent for the initial key in a trigger is that Key Mapper has no way of knowing if you are going to trigger the keymap or not so it assumes you are because otherwise your key won't be remapped.

**Comment by sds100** [comment]
I could actually make that an option for each key in a trigger. That would fix the problem because the shift key doesn't need to be consumed since it doesn't do anything on it's own.

**Comment by cauerego** [comment]
not sure what you mean, but sounds great! 🤣

it actually also happens with control key, but it's not as noticeable as with shift, due to their nature.

**Comment by sds100** [comment]
developer todo
- [ ] create flag property for Key object
- [ ] migrate old flag to key specific flag
- [ ] add the flag to not override the default behaviour by default to the appropriate keys. E.g Shift, Ctrl, Alt
- [ ]

**Comment by sds100** [comment]
implemented

**Comment by sds100** [comment]
squeezing into 2.1 release because it affects how data is stored in the database. I want as few users as possible on an outdated schema.
