### ISSUE TITLE
Feature request: KeyMapper intent receiver to trigger keymaps via intent

### ISSUE THREAD

**Issue by sudomain** [sds100/KeyMapper#490]
Developer checklist (i like to keep this at the top of the issue so I don't forget):

- [x] Test with apps that can send Intents. E.g Tasker and Automate
- [x] show a uuid for a keymap when configuring a keymap
- [x] tap on the uuid to copy it to the clipboard
- [x] add tutorial in website. add buttons so it is easy to copy the Intent action name and the extra name.
- [x] For Debug and Ci Builds `.debug` and `.ci` need to be appended to the package name, action and extra name.
- [x] recommend putting Key Mapper as the package for the Intent so that Key Mapper is the only app that will receive the Intent.
- [x] add a help button next to the button which links to the section on the website.
- [x] migration

It would be cool if we could send an intent to KeyMapper in order to trigger a keymap, especially one with the `tap coordinates` action

**Comment by sds100** [comment]
I think that is out of the realm of "key mapping" so I don't really want to add that. The countless automation apps on the Play Store must be able to do that? Like Tasker and Automate.

**Comment by sds100** [comment]
Although I have added an app shortcut to open actions and I'm planning on a Tasker shortcut so I will implement this eventually. I just need to figure out a secure way to do it because if designed incorrectly any app could potentially broadcast an Intent to do anything to your device through Key Mapper.

I would probably decouple this feature from keymaps, like I did with the Key Mapper app shortcut. I would probably add a screen where you can create a list of actions and assign it an ID and then you would broadcast an Intent with that ID to Key Mapper. Key Mapper will then receive that ID and will perform the list of actions with that ID.

**Comment by sudomain** [comment]
> The countless automation apps on the Play Store must be able to do that? Like Tasker and Automate.

Thank you for the suggestions, but my personal preference would be to only trust FOSS apps with a capability such as this.

> I just need to figure out a secure way to do it because if designed incorrectly any app could potentially broadcast an Intent to do anything to your device through Key Mapper.

There are a few apps on FDroid that make use of the [OpenKeyChain](https://github.com/open-keychain/open-keychain) app for PGP operations. OpenKeyChain can allow user-approved apps access to encrypt and/or sign with certain keys (without actually giving access to the key iirc). I think sufficient security could be achieved if users created a dedicated signing key for sending intents to KeyMapper and they had to whitelist the apps that could sign with this key.

**Comment by sds100** [comment]
I think that is a bit overkill. It is extremely unlikely anyone on the internet has a popular app that would want to interfere with this key mapper so it only needs minimal security. 😄

I think just generating a random UUID for the action list is sufficient. No app can guess the ID that way and the user can't make a "bad password". It will be up to the user to ensure that the Intent has io.github.sds100.keymapper set as the package so that other packages don't receive the intent.

**Comment by sds100** [comment]
implemented

**Comment by sds100** [comment]
Intent Action is `io.github.sds100.keymapper.TRIGGER_KEYMAP_BY_UID`
Intent Extra is `io.github.sds100.keymapper.KEYMAP_UID`. The value is a string with the UID of the keymap. You can get this by turning on "Trigger By Intent" in the keymap.

**Comment by sds100** [comment]
implemented
