### ISSUE TITLE
crash when getting app icon for app shortcut action that isn't installed

### ISSUE THREAD

**Issue by allanlaal** [sds100/KeyMapper#506]
keeps crashing when I opened
both with Play store current public and beta

I sent bugreports via the Android crash dialog for both. stopped the app and cleared cache beforehand

**Comment by sds100** [comment]
hello,

which device do you have?
which version of Key Mapper are you using? make sure Key Mapper is fully updated. There was an issue in Beta 2 that Key Mapper would crash on Android 6 and older but this was fixed in Beta 3.

**Comment by allanlaal** [comment]
Key Mapper 2.1.0-beta.4 on an Android 6.0 with kernel 3.18.19

**Comment by sds100** [comment]
I can't crash Key Mapper on a Android 6 emulator. Does it crash instantly on a fresh install? Could you crash the app again and then get me a bug report? Here is a guide on how to get a bug report... **https://www.youtube.com/watch?v=2sZ-5Os6_Cs**. Make sure to email me the bug report because there could be identifiable information in there.

**Comment by allanlaal** [comment]
@sds100  I just sent a bugreport to the gmail in the video :)

**Comment by sds100** [comment]
Thank you for the bug report! I've now fixed your issue. The problem was that Key Mapper was trying to get an icon for an app shortcut action but since the app for the shortcut wasn't installed, it couldn't find it and crashed. A fix for now is to either wipe Key Mapper's data or reinstall the app that it can't find. Here is the package name of that app: com.mdiwebma.screenshot

**Comment by allanlaal** [comment]
can confirm: installing com.mdiwebma.screenshot fixed the issue in beta-4 

thank you! :)

**Comment by sds100** [comment]
Amazing
