### ISSUE TITLE
App complains of "Battery Optimizations" being enabled despite the opposite

### ISSUE THREAD

**Issue by MKindy** [sds100/KeyMapper#547]
In fact, it's been disabled and unchangeable since the app was installed. See attached. 

### App:
![Screenshot_20210113-161936_Key Mapper](https://user-images.githubusercontent.com/1372854/104517526-c8bce500-55bb-11eb-96f9-740761e0a2dc.jpg)

### Battery Optimizations (completely disabled):
![Screenshot_20210113-162000_Settings](https://user-images.githubusercontent.com/1372854/104517553-d6726a80-55bb-11eb-9c8f-1fc742381dec.jpg)

### Phone Info: 
![Screenshot_20210113-162335_Settings](https://user-images.githubusercontent.com/1372854/104517570-de320f00-55bb-11eb-92f4-2cb8baff64c0.jpg)

**Comment by sds100** [comment]
if you close and open the app again does it change?

**Comment by Trollserver** [comment]
Everything is fine but it's crashing on my Huawei - I need to restart phone

Dňa št, 14. jan 2021, 2:32 sds100 <notifications@github.com> napísal(a):

**Comment by MKindy** [comment]
@sds100 No, it persists through app restarts and phone restarts. This is also after a factory reset. I can get you a list of other apps installed if you like, I haven't had time to do much after the factory reset so there's only a handful of apps installed.

**Comment by sds100** [comment]
I have no idea why its disabled. I've never seen that before and I have no idea how to do that. I've only seen some system apps like Google Play Services have it disabled. I really have no idea how this is happening. I'm pretty confident in the logic behind that warning. It's very simple because it all it does is ask the system "is key mapper being optimised?" and its up to the system to say yes or no. since its disabled and the system is saying that its not optimised then I'm leaning towards the system being at fault. how did you install Key Mapper?

**Comment by MKindy** [comment]
F-droid, yeah, version 2.2.0-beta-1. I did the next obvious thing and reinstalled it, and now it's behaving as expected; I can even turn on and off battery optimizations now. My guess is that, in my first installation, something went wrong with Android showing optimizations as being disabled when they weren't, and also preventing the feature from being toggled at all (so, a fault in the system rather than your program). Since it's working as it should be now, and was likely always an Android glitch, I'm gonna go ahead and close this report.

**Comment by sds100** [comment]
cool!
