### ISSUE TITLE
Hide logging warning

### ISSUE THREAD

**Issue by GL513** [sds100/KeyMapper#675]
Add a toggle switch to optionally turn off the warning at the top with the button. I have accidently clicked this a few times when i didnt mean to. 
This would also be really nice since Im always going to be logging, because I like helping out with debug.

**Comment by sds100** [comment]
Are you fine with just hiding all the alerts at the top of the home screen? There is a setting to do that already. Since you know how to use the app and are pretty experienced with it, none of the buttons up there really help you.

**Comment by GL513** [comment]
> Are you fine with just hiding all the alerts at the top of the home screen? There is a setting to do that already. Since you know how to use the app and are pretty experienced with it, none of the buttons up there really help you.

I know, but i was wanting to only hide the specific warning, because i wanted to know  if something is actually wrong.

**Comment by sds100** [comment]
I think this is too much when it comes to fine tuning. The reason why the warning is shown is because if someone has a slower device then it may add noticeable input latency to their key map. If they forget that it is on then they may think this is a bug. I think you're better off hiding the alerts because the only "error" is the accessibility service being off but there is a button for this in the home screen menu. All the others are warnings for features that if turned on and forgotten about can "break" the app from their point of view.
You know what you're doing so these alerts are pointless.
