### ISSUE TITLE
i cant stop service when my phone is locked PPPPPPLLLLLLLLZZZZZZ HELP MEEEEEE

### ISSUE THREAD

**Issue by xxxxxxzzxzsa** [sds100/KeyMapper#682]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://sds100.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by GL513** [comment]
If you have discord, please consider visiting there for more support from the community. If you would rather not, you can talk to me :)
When did this start, what triggered it, and what behaviour do you expect? Also, it would be very nice if you could provide screenshots and otger useful information of your keymaps so i can help. Im not a developer, but since the main devs (sds100 and Jambler) are currently not active, im going to try my best by myself since ive been around a few or more android things.
