### ISSUE TITLE
No screen-off action work on note 20 ultra.

### ISSUE THREAD

**Issue by Soxial** [sds100/KeyMapper#692]
HI, Im a long time time Button Mapper user and recently I started using your APP, KeyMapper, I migrated from ButtonMapper I was expecting for screen off actions to work in this app but they dont. I HAVE no root and Button Mapper allows for screen off actions WITHOUT ROOT. But in your app you are requiered root?? Will you please add the same feature Button Mapper has, is the only reason why I have not uninstall Button Mapper. I like your app but the Profiles GUI also need a bit of cleanup as it gets messy once you add alot of actions. THANK YOU for your app is good but Im sure it will be a great APP.

**Comment by sds100** [comment]
It isn't trivial to get screen off actions working because Android doesn't support it easily. There is already an issue for adding support for volume buttons when the screen is off and media is playing https://github.com/sds100/KeyMapper/issues/501. Does Button Mapper allow you to detect _any_ buttons (like keyboard buttons) when the screen is off or only the volume buttons?

**Comment by Soxial** [comment]
I honestly have not used a keyboard on my phone, I wouldnt know. This is a suggestion but would you add a "delay single press" option so when you do double press action there wont be a single press action trigger while doing your double press action.. Thank you.
