### ISSUE TITLE
Failed to find accessibilty node!

### ISSUE THREAD

**Issue by JonnyTech** [sds100/KeyMapper#771]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] squash and merge
- [x] delete branch

**Discord message link/email recipient**

**Describe the bug**
The subject message is shown when long pressing a button, the action is not performed. Other mappings work ok.

**To Reproduce**
My phone has a menu buton and no recents button
Map menu button to recents action.
Map menu button long press to menu action.
Long press menu button.

Upload a backup of your keymaps. [mappings.zip](https://github.com/sds100/KeyMapper/files/7071596/mappings.zip)

**Expected behavior**
Action (show menu) should be performed.

**Screenshots**
![keymaperror](https://user-images.githubusercontent.com/3584732/131232921-04caaf59-32d8-46a9-af2f-ba796ba5af4d.png)

**Smartphone (please complete the following information):**
 - Device: Xioami
 - Android version: AOSP 10

**Additional context**

**Comment by GL513** [comment]
Do you have ADB on your phone? You can enable the accessibility service using that if needed. Also, possibly grant WRITE_SECURE_SETTINGS while you're at it, since KeyMapper can most of the time re-enable itself when the system removes the service due to no feedback, and that would be either because the app isn't running *at all*, or because of other things, such as battery optimization, or just spastic things like Samsung killing apps all the time, even with battery optimization. That could save you from having to enable it's accessibility service from ADB in the future.

**Comment by sds100** [comment]
This issue isn't related to that. The way the open menu action works on non-rooted/no shizuku device is it looks for the menu button and then taps it for you instead of inputting the key event. But not all menus work with the way that I'm trying to detect them. This error shouldn't show up for this kind of action because it is normal that the menu can't always be found. E.g if there is no menu on screen at all.
________________________________

**Comment by sds100** [comment]
fixed

**Comment by JonnyTech** [comment]
Thanks guys. Is there a prebuilt apk that I can try to test the fix? My phone is rooted. All other keypresses work fine so shows that accessibilty permission is granted correctly. Older versions of keymapper (v1.x iirc) worked as expected.

**Comment by sds100** [comment]
Yeah, join the Discord server at www.keymapper.club and you can download the alpha builds in the #testing-builds channel. I'm going to try to get the first 2.4.0 beta out today with this fix as well

**Comment by sds100** [comment]
Since you are rooted you should turn on the root permission setting in Key Mapper's settings. This will make the menu action work 100% reliably instead of using the accessibility nodes.

**Comment by JonnyTech** [comment]
Thanks, as I am not a Discord user, I shall wait for the beta release.

I thought that I had enabled root access but looks like it was only temporary. Adding it back fixed the issue.

Great work, really appreciate the quick responses.

**Comment by sds100** [comment]
Cool, no problem. The builds in the Discord are just forwarded from GitHub Actions. You can get the "artifacts" from the automated builds by clicking on "Actions" at the top of the repo and going to the "develop" workflow.

**Comment by JonnyTech** [comment]
👍
